# Generated by Django 5.2.1 on 2025-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('screen_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер экрана')),
                ('processor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Процессор')),
                ('cores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество ядер')),
                ('ram', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём памяти (ГБ)')),
                ('storage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ёмкость накопителя (ГБ)')),
            ],
        ),
    ]
